### ISSUE TITLE
SignatureVersion 2 no longer works

### ISSUE THREAD

**Issue by longwave** [morgoth/alexa#13]
This gem only implements AWS SignatureVersion 2 but https://docs.aws.amazon.com/AlexaWebInfoService/latest/CalculatingSignatures.html notes this is no longer available

> Signature version 4 is described below. Signature V2 will  be deprecated on Feb 1, 2018. As of November 25, 2017 you must use  signature version 4.

There seem to be some forks that do implement v4 such as https://github.com/Welovroi/alexa

**Comment by morgoth** [comment]
Fixed in 0.7.0
